name: Build Test Image

on:
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

jobs:
  build:
    name: Build Test Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v2.9.1

      - id: docker_build
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: false
          load: true
          tags: ${{ github.repository }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - run: ./aws --version
        env:
          IMAGE: ${{ github.repository }}:test
